name: dartshell
description: Easily write and run shell-like scripts with dart.
version: 0.1.0
repository: https://github.com/komposten/dartshell

executables:
  dartshell:

environment:
  sdk: ^3.12.2

dependencies:
  analyzer: ^14.1.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
